### ISSUE TITLE
no type or protocol named 'UIApplicationOpenURLOptionsKey' When previewing on IOS

### ISSUE THREAD

**Issue by heavenchains** [cbaggers/Fuse.Firebase#24]
I get this error when I build:

The following build commands failed:
	CompileC /Users/mostafa/Desktop/Fuse.Firebase-master/AuthExample/build/iOS/Debug/build/Build/Intermediates/Pods.build/Release-iphoneos/FBSDKCoreKit.build/Objects-normal/armv7/FBSDKAccessToken.o FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKAccessToken.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/mostafa/Desktop/Fuse.Firebase-master/AuthExample/build/iOS/Debug/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKApplicationDelegate.h:75:35: error: no type or protocol named 'UIApplicationOpenURLOptionsKey'
(15.1 s)

**Comment by cbaggers** [comment]
How are you building the project? Has this been working previously?

**Comment by heavenchains** [comment]
No it hasn't been working however, I talked on slack to the fuse team and someone told me to update xcode which I did I have version 8+ now but when I fire this fuse build -t=iOS -DCOCOAPODS I get this error now : 

Configuring
WARNING: .unoconfig: 'PackageSourcePaths' is deprecated -- use 'Packages.SourcePaths'
Target is up-to-date -- stopping build (pass --force to override)
Building iOS app
Downloading dependencies
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
(20.0 s)

Build completed in 20.25 seconds
