### ISSUE TITLE
 error: package com.google.android.gms.tasks does not exist

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [cbaggers/Fuse.Firebase#25]
Hi,

I'm getting the following error on preview: fuse preview -t=Android

`../Fuse.Firebase/AuthExample/build/Android/Preview/AuthExample/app/src/main/java/com/foreign/Firebase/Authentication/AuthService.java:23: error: package com.google.android.gms.tasks does not exist`

What might be wrong here?

Thanks,
Unnikrishnan B.

**Comment by cbaggers** [comment]
You arent building with Gradle for a start. Please see the docs https://github.com/cbaggers/Fuse.Firebase/wiki/Getting-up-and-running-with-the-Example-Project which show how to build the project

**Comment by UnnikrishnanBhargavakurup** [comment]
Hi, 

We have an issue with gradle build in fuse, its already mentioned here: https://github.com/cbaggers/Fuse.Firebase/issues/23

Could please look into it?

Thanks.

**Comment by cbaggers** [comment]
You said you were doing this `fuse preview -t=Android` this is not building with gradle. The other issue is being looked into though, thanks for raising it.

**Comment by fusebuild** [comment]
The forum thread [On preview getting the error: package com.google.android.gms.tasks does not exist](https://www.fusetools.com/community/forums/bug_reports/on_preview_getting_the_error_package_comgoogleandr) posted by unnikrishnan was linked to this issue.
