### ISSUE TITLE
Firebase/Firebase.h file not found

### ISSUE THREAD

**Issue by princefr** [cbaggers/Fuse.Firebase#8]
Hi,
I can not build the app in Xcode because of Firebase/Firebase.h file not found

**Comment by cbaggers** [comment]
DId you build with `-DCOCOAPODS`?

**Comment by princefr** [comment]
I built it with -DCOCOAPODS 

i have this in the console

```
No matching provisioning profiles found: No provisioning profiles matching an applicable signing identity were found.
** BUILD FAILED **
```

my profile on Xcode are good don't really know why this error is occurring , i'm also facing build failing in using griddle build on android version

**Comment by princefr** [comment]
Any help about this?

**Comment by jwhscholten** [comment]
Same here, looks like the firebase library isn't being linked properly?

**Comment by bolav** [comment]
Can you try to compile it with `-d` as well, to open it in Xcode? It might set up the wrong provisioning profile.

**Comment by bolav** [comment]
@jwhscholten, what issue are you getting?

**Comment by jwhscholten** [comment]
@bolav 

`No matching provisioning profiles found: No provisioning profiles matching an applicable signing identity were found.
** BUILD FAILED **`

Running fuse build -t=iOS -d -DCOCOAPODS is working for me! Thanks a bunch.
